title: SWAT Documentation
description: Documentation for the SWAT project
theme: just-the-docs

logo: "/assets/images/logo.png"

url: https://swat-project.github.io/docs

aux_links:
  Github Repository: https://github.com/swat-project/SWAT
